import json

a = json.loads('{\n    "water quality": false,\n    "water testing request": false,\n    "product claim": false\n}')

print(type(a))

all_false = not any(a.values())
print(all_false)

'|    | Parameter List   | Units   |   PUB Drinking Water Standard Average | PUB Drinking Water Standard Range   | US EPA Standards (updated May 2009)   | WHO Drinking-water Guidelines 2022 (4th Edition with 1st and 2nd addenda)   | Environmental Public Health (Water Suitable for Drinking) (No.2) Regulations 2019   |   EU Directive (2020/2184)  |\n|    |                  |         |                                       |                                     |                                       |                                                                             |                                                                                     |                             |\n|    |                  |         |                                       |                                     |                                       |                                                                             |                                                                                     |                 16 Dec 2020 |\n|---:|:-----------------|:--------|--------------------------------------:|:------------------------------------|:--------------------------------------|:----------------------------------------------------------------------------|:------------------------------------------------------------------------------------|----------------------------:|\n| 28 | Aluminium        | mg/L    |                                 0.002 | < 0.019 - 0.083                     | 0.05-0.2 (Sec MCL)                    | 0.9 (Health-based)                                                          | (COP)                                                                               |                         0.2 |\n|    |                  |         |                                       |                                     |                                       |                                                                             | 0.1 (all WWs except PTWW),                                                          |                             |\n|    |                  |         |                                       |                                     |                                       |                                                                             | 0.2 (PTWW)                                                                          |                             |\n| 49 | Lead             | ug/L    |                                 0.5   | < 0.5 - 1.2                         | 15 (action level, see Note 2)         | 10                                                                          | 10                                                                                  |                         5   |'